In [1]:
# H1 TITLE
## H2 TITLE


In [72]:
print("Hello there ?")


Hello there ?


## Exercise 1: Your first NumPy array

In [7]:
import numpy as np

your_np_array = np.array([
    42,                        # integer
    3.14,                      # float
    "Hello NumPy",             # string
    {"key": "value"},          # dictionary
    [1, 2, 3],                 # list
    (4, 5, 6),                 # tuple
    {7, 8, 9},                 # set
    True                        # boolean
], dtype=object)               # dtype=object allows mixed types

for i in your_np_array:
    print(type(i))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


## Exercise 2: Zeros


In [10]:
#creating a 1D array
zeros_array = np.zeros(300)
print(zeros_array)

#reshaping to 3D array
zeros_array_reshaped = zeros_array.reshape(3, 100)
print(zeros_array_reshaped)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0

## Exercise 3: Slicing

---

np.arange(start, stop) generates a sequence of numbers starting from start up to, but not including, stop.
In our example, np.arange(1, 101) produces numbers from 1 to 100 because the start is 1 and the stop value 101 is exclusive

In [17]:
arr = np.arange(1, 101)
print(arr)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [19]:
#array of all ods
odd_arr = arr[arr % 2 != 0]
print(odd_arr)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [24]:
#array of all even
even_arr = arr [arr % 2 == 0]
print(even_arr)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [26]:
#array of all even arrays in reverse
reverse_even_arr = arr [arr % 2 == 0][::-1]
print(reverse_even_arr)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [27]:
#Set every 3rd element (starting from the second) to 0
arr_copy = arr.copy() # keeping original intact
arr_copy[1::3] = 0
print(arr_copy)


[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


- arr % 2 != 0 selects odd numbers.

- [::-1] reverses an array.

- 1::3 selects every 3rd element starting from index 1.

## Understanding NumPy Arrays

NumPy arrays are like Python lists but more efficient for numerical computations. They allow:

- **Fast operations** on large datasets
- **Vectorized calculations** without loops
- **Multi-dimensional arrays** (1D, 2D, 3D, etc.)

Example: 
```python
import numpy as np
arr = np.arange(1, 101)
print(arr)


## Exercise 4: Random

NumPy lets us generate random numbers in different ways. **rand()** gives random decimals between 0 and 1, **randint(a, b)** gives whole numbers between a and b-1, **randn()** generates numbers from a normal distribution (centered around 0), and **choice()** randomly picks elements from a list we provide. This makes it easy to simulate data or test algorithms

---

- np.random.seed(888) makes results reproducible.

- randn() generates numbers from a normal distribution (bell curve).

- randint(a, b) generates integers between a and b-1, so we add +1 to the upper bound to include it.

- Shapes (100,), (8,8), (4,2,5) match exactly what the exercise requires.


In [36]:
#Step 0: Import and set seed
import numpy as np

#setting the seed makes result reproducible
np.random.seed(888)




In [31]:
#1. One-dimensional array of size 100 with a normal distribution
normal_arr = np.random.randn(100)
print(normal_arr)

[-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08510762e-01
 -1.40481067e+00 -6.54547

In [34]:
#2. Two-dimensional 8×8 array of random integers from 1 to 10 (inclusive)
rand_ints_2d = np.random.randint(1, 11, size=(8,8)) # 11 because stop is exclusive
print(rand_ints_2d)

[[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]


In [35]:
#3. Three-dimensional 4×2×5 array of random integers from 1 to 17 (inclusive)
rand_ints_3d = np.random.randint(1, 18, size=(4, 2, 5))   # 18 because stop is exclusive
print(rand_ints_3d)


[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]


## Exercise 5: Split, Concatenate, Reshape Arrays

The goal of this exercise is to learn how to split arrays, concatenate them, and reshape them into new dimensions.

---



In [39]:
### Step 1: Generate arrays
arr1 = np.arange(1, 51)     # integers from 1 to 50

print(arr1)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [40]:
arr2 = np.arange(51, 101)   # integers from 51 to 100

print(arr2)

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [41]:
##Step 3: Concatenate both arrays
arr_full = np.concatenate([arr1, arr2])
print(arr_full)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [42]:
##Step 4: Reshape into 10×10
arr_reshaped = arr_full.reshape(10, 10)
print(arr_reshaped)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


## Exercise 6: Broadcasting and Slicing

The goal of this exercise is to learn how to access and manipulate values of n-dimensional arrays efficiently using slicing and broadcasting.




In [46]:
### Part A: Create a 9×9 array with borders and a pattern
arr = np.ones((9, 9), dtype=np.int8)
print(arr)


[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [50]:
#Step 2: Use slicing to insert zeros inside (keeping border = 1)
ar = arr[1:-1, 1:-1] = 0
#Add the inner pattern
arr[2, 2:7] = 1
arr[3, [2, 6]] = 1
arr[4, [2, 4, 6]] = 1
arr[5, [2, 6]] = 1
arr[6, 2:7] = 1

print(arr)


[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [52]:
#Using broadcasting create an output matrix based on the following two arrays:
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)

#Multiply using broadcasting
result = array_1[:, np.newaxis] * array_2   # shape (5,3)
print(result)



[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


## Exercise 7: Handling Missing Data with np.where

Here we handled NaN (missing values) in a dataset of student grades without using loops.

✅ Problem

We have a (10 × 2) array of grades from two exams. Some students missed the first exam, so their score is stored as NaN.

We want to create a third column:

- If the first exam grade is available → use it.

- If it’s missing (NaN) → use the second exam grade.

In [54]:
import numpy as np

# Step 1: Generate dataset
generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
grades[[1, 2, 5, 7], [0, 0, 0, 0]] = np.nan
print("Original grades:\n", grades)

# Step 2: Create third column using np.where
third_col = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])

# Step 3: Concatenate third column to grades
grades_final = np.column_stack((grades, third_col))

print("\nFinal grades with 3rd column:\n", grades_final)


Original grades:
 [[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]

Final grades with 3rd column:
 [[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


## Exercise 8: Wine

In [59]:
import numpy as np

# Step 1: URL of the CSV
url = "https://learn.zone01kisumu.ke/api/content/root/public/subjects/ai/numpy/data/winequality-red.csv"

# Step 2: Load data with genfromtxt
data = np.genfromtxt(url, 
                     delimiter=";", 
                     skip_header=1, 
                     dtype=np.float32)

# Step 3: Initial checks
print("Shape of data:", data.shape)        # how many rows and columns
print("First 5 rows:\n", data[:5])         # show first 5 rows
print("Has any NaNs:", np.any(np.isnan(data)))
print("Memory usage (bytes):", data.nbytes)



# If the bytes count ≠ 76800, check: dtype and shape


Shape of data: (1599, 12)
First 5 rows:
 [[7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00 5.000e+00]
 [7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.800e+00 7.600e-01 4.000e-02 2.300e+00 9.200e-02 1.500e+01 5.400e+01
  9.970e-01 3.260e+00 6.500e-01 9.800e+00 5.000e+00]
 [1.120e+01 2.800e-01 5.600e-01 1.900e+00 7.500e-02 1.700e+01 6.000e+01
  9.980e-01 3.160e+00 5.800e-01 9.800e+00 6.000e+00]
 [7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00 5.000e+00]]
Has any NaNs: False
Memory usage (bytes): 76752


In [62]:
#2  Extract the 2nd, 7th, and 12th rows
selected_rows = data[[1, 6, 11], :]
print(selected_rows)

# Remove NaNs from each row
cleaned_rows = [row[~np.isnan(row)] for row in selected_rows]
cleaned_rows = np.array(cleaned_rows, dtype=np.float32)
print(cleaned_rows)




[[7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00 5.000e+00]
 [7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
  9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]]
[[7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00 5.000e+00]
 [7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
  9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]]


In [64]:
# 3 determine if alcohol percentage greater than 20%
alcohol = data[:, 10]   # get all rows, column 10 (alcohol %)

has_high_alcohol = np.any(alcohol > 20)
print(has_high_alcohol)



False


In [65]:
# 4 calculate % alcohol of all wine
#Step 1: Extract the alcohol column
alcohol = data[:, 10]

#Step 2: Exclude NaN values (just in case)
alcohol_no_nan = alcohol[~np.isnan(alcohol)]

#Step 3: Compute mean
avg_alcohol = np.mean(alcohol_no_nan)
print("Average alcohol %:", avg_alcohol)



Average alcohol %: 10.422984


In [66]:
# 5: Statistical measures for the pH values.

#Step 1: Extract the pH column
ph = data[:, 8]

#Step 2: Remove NaN values (if any)
ph_no_nan = ph[~np.isnan(ph)]

#Step 3: Compute the statistics
ph_min = np.min(ph_no_nan)
ph_max = np.max(ph_no_nan)
ph_25 = np.percentile(ph_no_nan, 25)
ph_50 = np.percentile(ph_no_nan, 50)   # same as median
ph_75 = np.percentile(ph_no_nan, 75)
ph_mean = np.mean(ph_no_nan)

print("pH Statistics:")
print("Min:", ph_min)
print("Max:", ph_max)
print("25th percentile:", ph_25)
print("50th percentile (median):", ph_50)
print("75th percentile:", ph_75)
print("Mean:", ph_mean)


pH Statistics:
Min: 2.74
Max: 4.01
25th percentile: 3.2100000381469727
50th percentile (median): 3.309999942779541
75th percentile: 3.4000000953674316
Mean: 3.3111134


In [67]:
#6: Average quality for wines with the 20% least sulphate content.
#Step 1: Extract the sulphates and quality columns

sulphates = data[:, 9]
quality = data[:, 11]

sulphates_20 = np.percentile(sulphates, 20)
print("20th percentile of sulphates:", sulphates_20)

#Create a boolean mask for wines with sulphates below this threshold
mask = sulphates < sulphates_20

low_sulphate_quality_mean = np.mean(quality[mask])
print("Average quality (20% least sulphates):", low_sulphate_quality_mean)



20th percentile of sulphates: 0.5400000214576721
Average quality (20% least sulphates): 5.1854305


In [68]:
#7: Mean of all variables for best and worst quality wines
quality = data[:, 11]

best_quality = np.max(quality)
worst_quality = np.min(quality)

print("Best quality:", best_quality)
print("Worst quality:", worst_quality)

mask_best = quality == best_quality
mask_worst = quality == worst_quality

mean_best = np.mean(data[mask_best], axis=0)
mean_worst = np.mean(data[mask_worst], axis=0)

print("Mean values for best quality wines:\n", mean_best)
print("\nMean values for worst quality wines:\n", mean_worst)



Best quality: 8.0
Worst quality: 3.0
Mean values for best quality wines:
 [ 8.566666    0.4233333   0.39111114  2.5777776   0.06844445 13.277778
 33.444443    0.99521226  3.2672222   0.76777774 12.094444    8.        ]

Mean values for worst quality wines:
 [ 8.359999    0.8845      0.17099999  2.6350002   0.12249999 11.
 24.9         0.997464    3.398       0.57000005  9.955       3.        ]


## Exercise 9: Football tournament

In [71]:
import numpy as np
import itertools

# Step 1: Load forecast matrix (10x10)
url = "https://learn.zone01kisumu.ke/api/content/root/public/subjects/ai/numpy/data/model_forecasts.txt"
matrix = np.genfromtxt(url, delimiter=',')

# Step 2: Create list of 10 teams
teams = np.arange(10)

# Step 3: Generate all possible team pairs
all_pairs = list(itertools.combinations(teams, 2))

# Step 4: Function to calculate sum of squared differences for a given set of matches
def pairing_cost(pairs):
    return sum(matrix[t1, t2]**2 for t1, t2 in pairs)

# Step 5: Generate candidate match combinations
# We pick 5 pairs that do not overlap (i.e., no team appears twice)
# Use a simple method with itertools.permutations for illustration (may not be fully optimal)
def generate_non_overlapping_matches(pairs):
    # Try all combinations of 5 pairs
    for candidate in itertools.combinations(pairs, 5):
        # Flatten all teams in candidate pairs
        flat = [t for pair in candidate for t in pair]
        # Check if all teams are unique
        if len(set(flat)) == 10:
            yield candidate

# Step 6: Find the combination with minimum sum of squared differences
best_cost = float('inf')
best_matches = None

for candidate in generate_non_overlapping_matches(all_pairs):
    cost = pairing_cost(candidate)
    if cost < best_cost:
        best_cost = cost
        best_matches = candidate

# Step 7: Format result as 2x5 array
result = np.array(best_matches).T
print("Best matches (Team1 vs Team2):")
print(result)


Best matches (Team1 vs Team2):
[[0 1 2 3 5]
 [8 7 9 4 6]]
